version: 2
jobs:
  build:
    working_directory: ~/dazl
    docker:
      - image: circleci/python:3.6.9
      - image: digitalasset/daml-sdk:0.13.51
        command: |
          daml sandbox
    steps:
      - run:
          name: Configure environment
          command: |
            poetry config virtualenvs.in-project true
      - checkout
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "python/poetry.lock" }}
      - run:
          command: |
            make -C python deps
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "python/poetry.lock" }}
          paths:
            - "python/.venv"
      - run:
          name: Python unit tests
          command: |
            make -C python test
      - run:
          name: Python integration tests
          command: |
            make -C python integration-test
      - run:
          name: Python packaging
          command: |
            make -C python package
      - run:
          name: Run Blackduck Detect
          command: |
            bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) ci-build digitalasset_dazl master --logging.level.com.synopsys.integration=DEBUG --detect.python.python3=true
      - store_test_results:
          path: python/test-results
      - persist_to_workspace:
          root: ~/dazl
          paths:
            - python/dist

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: blackduck
